### PR TITLE
Fix copy-paste error and improve formatting

### PR DESCRIPTION
**Pull request by juergen-walter**

### CODE REVIEW

**Comment by williamkeyes** [comment]
I've fixed these in the DRAFT version: https://help.sap.com/docs/cloud-logging/sap-cloud-logging/configuration-parameters?state=DRAFT
It should show up in the next nightly build.

**Comment by williamkeyes** [comment]
This is fixed in the DRAFT version. If it looks good, I'll push it out to PROD. 
https://help.sap.com/docs/cloud-logging/sap-cloud-logging/configuration-parameters?state=DRAFT

**Comment by juergen-walter** [comment]
Push it to prod please

**Comment by williamkeyes** [comment]
Thanks, @juergen-walter. I have pushed the changes out to PROD. They should show up after the next build.

**Comment by juergen-walter** [comment]
Fix is still not available here: https://help.sap.com/docs/cloud-logging/cloud-logging/configuration-parameters?version=Cloud  ....

**Comment by juergen-walter** [comment]
I would assume it is propagated after merge, right?

**Review by williamkeyes — APPROVED** [review]

**Review by williamkeyes — APPROVED** [review]
LGTM

**Comment by williamkeyes** [comment]
PROD builds are done weekly, usually on either Wednesday or Thursday. So the changes should show up in PROD later in the week. I apologize I wasn't more clear on this earlier.

**Comment by williamkeyes** [comment]
The changes are now available in PROD
https://help.sap.com/docs/cloud-logging/sap-cloud-logging/configuration-parameters

**Review by keyes-bill — APPROVED** [review]
LGTM

**Pull request merged**
