### PR TITLE
Highlight size-based deletion in service plan description

### PR DESCRIPTION
**Pull request by juergen-walter**
formatting change only

### CODE REVIEW

**Comment by juergen-walter** [comment]
Should look the same as https://help.sap.com/docs/cloud-logging/cloud-logging/ingest-via-kyma-runtime?version=Cloud

**Comment by juergen-walter** [comment]
image

**Review by pc-jedi — APPROVED** [review]
🦖 

LGTM, but waiting for @keyes-bill review.

**Comment by williamkeyes** [comment]
I've made the changes to the DRAFT version of the documentation. 
https://help.sap.com/docs/cloud-logging/sap-cloud-logging/service-plans?state=DRAFT

**Comment by juergen-walter** [comment]
Looks good 👍

**Comment by williamkeyes** [comment]
I've pushed this out to PROD. Should be available within a few hours of this writing.

**Review by williamkeyes — APPROVED** [review]
I've made the changes as requested and pushed out to PROD. Should be available Wed or Thurs May 8-9.

**Comment by je-hal** [comment]
@keyes-bill : This looks to me as if it was a valuable contribution. Please be reminded to do the following in such cases:
1. use label `contribution`.
2. Use one of the `type/` labels.
3. Merge the pull request. Closing pull requests means you rejected the change and contributors won't get any credits for it.

Thanks

**Pull request closed without merging**
